//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Student
    {
        public int ClassStudentId { get; set; }
        public int ClassId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual StudentDetail StudentDetail { get; set; }
    }
}
