//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public Nullable<int> Sinhala { get; set; }
        public Nullable<int> Maths { get; set; }
        public Nullable<int> English { get; set; }
        public Nullable<int> SId { get; set; }
    
        public virtual StudentDetail StudentDetail { get; set; }
    }
}
