//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentDBEntities1 : DbContext
    {
        public StudentDBEntities1()
            : base("name=StudentDBEntities1")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    // configures one-to-many relationship
        //    modelBuilder.Entity<Mark>()
        //    .HasRequired<StudentDetail>(b => b.StudentDetail)
        //    .WithMany(a => a.Marks)
        //    .HasForeignKey<int?>(b => b.SId);
        //}

        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<StudentDetail> StudentDetails { get; set; }
    }
}
